[project]
name = "1-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pedro Ivo Bueno Sartório", email = "pedroivobu@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
1-rag = "1_rag:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
